version: '3.8'
services: 
  backend:
    build: ./backend
    ports:
      - "3333:3000"
    volumes:
      - ./backend:/app
    env_file:
     - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/.next